#!/usr/bin/zsh 
ca=$(qdbus org.kde.ActivityManager /ActivityManager/Activities CurrentActivity)
activity=$(<scripts/Activity/created.txt)
activites=()
d=0
setopt shwordsplit  
for i in $activity; do
	if [ $ca = $i ]
	then
		d=1
		xdotool key Meta + Tab;sleep 0.5;qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.RemoveActivity $ca
	else
		activites+="$i" 
	fi		
done
unsetopt shwordsplit
echo "$activites" > "scripts/Activity/created.txt"
if [ $d -eq 0 ] 
then
xdotool key Meta + Tab;sleep 0.5;qdbus org.kde.ActivityManager /ActivityManager/Activities org.kde.ActivityManager.Activities.StopActivity $ca;
fi
